<?php
/**
 * Reading, writing and normalising config/config.php, plus the session and
 * fatal-error helpers.
 *
 * Kept apart from bootstrap.php so install.php can use them without the
 * bootstrap's side effects — the installer has to keep working when the
 * database credentials in the config are wrong, which is exactly when the
 * bootstrap would abort.
 */

if (!defined('VEC_ROOT')) {
    define('VEC_ROOT', dirname(__DIR__));
}
if (!defined('VEC_APP')) {
    define('VEC_APP', VEC_ROOT . '/app');
}
if (!defined('VEC_VERSION')) {
    define('VEC_VERSION', '1.0.0');
}

/**
 * @return array|null null when config/config.php is absent or unreadable
 */
function vec_load_config()
{
    $file = VEC_ROOT . '/config/config.php';
    if (!is_file($file)) {
        return null;
    }
    $config = include $file;
    return is_array($config) ? $config : null;
}

/**
 * Fills in keys an older config file predates, so upgrading the code never
 * requires hand-editing config.php.
 *
 * @param array $config
 * @return array
 */
function vec_normalise_config($config)
{
    $defaults = array(
        'db' => array(
            'host' => 'localhost', 'port' => 3306, 'name' => '',
            'user' => 'root', 'pass' => '', 'socket' => '', 'prefix' => 'va_',
        ),
        'app' => array(
            'name' => 'ระบบติดตามศิษย์เก่า', 'timezone' => 'Asia/Bangkok',
            'env' => 'production', 'debug' => false,
        ),
        'session' => array('name' => 'VECALTS', 'lifetime' => 7200, 'secure' => false),
        'installed' => false, 'installed_at' => null, 'version' => VEC_VERSION,
    );
    if (!is_array($config)) {
        $config = array();
    }
    foreach ($defaults as $key => $value) {
        if (!isset($config[$key])) {
            $config[$key] = $value;
        } elseif (is_array($value)) {
            $config[$key] = array_merge($value, is_array($config[$key]) ? $config[$key] : array());
        }
    }
    return $config;
}

/**
 * var_export that emits array() syntax, valid on PHP 5.4 and 8 alike.
 *
 * @param mixed $value
 * @param int $indent
 * @return string
 */
function vec_var_export($value, $indent = 0)
{
    $pad = str_repeat('    ', $indent);
    if (is_array($value)) {
        if (!$value) {
            return 'array()';
        }
        $isList = (array_keys($value) === range(0, count($value) - 1));
        $lines = array();
        foreach ($value as $k => $v) {
            $key = $isList ? '' : var_export($k, true) . ' => ';
            $lines[] = $pad . '    ' . $key . vec_var_export($v, $indent + 1);
        }
        return "array(\n" . implode(",\n", $lines) . "\n" . $pad . ')';
    }
    if ($value === null) {
        return 'null';
    }
    if (is_bool($value)) {
        return $value ? 'true' : 'false';
    }
    if (is_int($value) || is_float($value)) {
        return (string) $value;
    }
    return var_export((string) $value, true);
}

/**
 * @param array $config
 * @return string PHP source for config/config.php
 */
function vec_config_export($config)
{
    return "<?php\n"
        . "/**\n"
        . " * Generated by install.php on " . date('Y-m-d H:i:s') . ".\n"
        . " * Safe to edit by hand; re-running the installer rewrites it.\n"
        . " */\n\n"
        . "// Refuse to run when requested directly over HTTP. The .htaccess in\n"
        . "// this directory does the same, but that file is ignored by nginx and\n"
        . "// by PHP's built-in server, so the guard lives here as well.\n"
        . "if (!defined('VEC_ROOT')) {\n"
        . "    header('HTTP/1.0 404 Not Found');\n"
        . "    exit;\n"
        . "}\n\n"
        . 'return ' . vec_var_export($config, 0) . ";\n";
}

/**
 * Writes config/config.php atomically.
 *
 * @param array $config
 * @return array array('ok' => bool, 'error' => string)
 */
function vec_write_config($config)
{
    $dir = VEC_ROOT . '/config';
    $file = $dir . '/config.php';

    if (!is_dir($dir) && !@mkdir($dir, 0775, true)) {
        return array('ok' => false, 'error' => 'สร้างโฟลเดอร์ config/ ไม่ได้');
    }
    if (!is_writable($dir) && !(is_file($file) && is_writable($file))) {
        return array('ok' => false, 'error' => 'โฟลเดอร์ config/ ไม่มีสิทธิ์เขียน');
    }

    // Write to a temp file first so a failed write cannot leave a truncated
    // config behind on a live site.
    $temp = $dir . '/config.php.tmp';
    if (@file_put_contents($temp, vec_config_export($config), LOCK_EX) === false) {
        return array('ok' => false, 'error' => 'เขียนไฟล์ config ชั่วคราวไม่สำเร็จ');
    }
    // Windows rename() will not overwrite, so remove the target first.
    if (is_file($file) && !@unlink($file) && !@copy($temp, $file)) {
        @unlink($temp);
        return array('ok' => false, 'error' => 'แทนที่ไฟล์ config เดิมไม่สำเร็จ');
    }
    if (is_file($temp) && !@rename($temp, $file)) {
        @unlink($temp);
        return array('ok' => false, 'error' => 'เปลี่ยนชื่อไฟล์ config ไม่สำเร็จ');
    }
    @chmod($file, 0640);

    // Opcache would otherwise keep serving the previous config.
    if (function_exists('opcache_invalidate')) {
        @opcache_invalidate($file, true);
    }
    return array('ok' => true, 'error' => '');
}

/**
 * Declares UTF-8 for the response, before anything is echoed.
 *
 * The HTTP Content-Type header overrides the document's <meta charset>, and
 * nothing declares UTF-8 on our behalf: PHP 5.4 still defaults
 * default_charset to ISO-8859-1, and a host with `AddDefaultCharset
 * windows-874` (common on Thai servers) stamps a legacy Thai charset on every
 * response. Either way the browser decodes our UTF-8 bytes as something else
 * and every Thai string renders as mojibake. Saying it ourselves settles it
 * whatever the server is configured to do.
 */
function vec_send_charset()
{
    @ini_set('default_charset', 'UTF-8');
    if (!headers_sent()) {
        header('Content-Type: text/html; charset=UTF-8');
    }
}

/**
 * Starts the session with settings that work on both target PHP versions.
 * @param array $sessionConfig
 */
function vec_start_session($sessionConfig = array())
{
    if (session_status() === PHP_SESSION_ACTIVE) {
        return;
    }
    $name = isset($sessionConfig['name']) ? $sessionConfig['name'] : 'VECALTS';
    $lifetime = isset($sessionConfig['lifetime']) ? (int) $sessionConfig['lifetime'] : 7200;
    $secure = !empty($sessionConfig['secure']);

    session_name($name);
    // The options-array form of session_set_cookie_params() only exists from
    // PHP 7.3, so use the positional signature available everywhere.
    session_set_cookie_params($lifetime, '/', '', $secure, true);
    @ini_set('session.use_only_cookies', '1');
    @ini_set('session.use_strict_mode', '1');
    @ini_set('session.gc_maxlifetime', (string) $lifetime);
    session_start();
}

/**
 * Renders a fatal error page and stops.
 *
 * @param string $title
 * @param string $detail
 * @param bool $showDetail
 */
function vec_fatal($title, $detail = '', $showDetail = false)
{
    if (!headers_sent()) {
        http_response_code(500);
        header('Content-Type: text/html; charset=utf-8');
    }
    $escape = function ($value) {
        return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
    };
    echo '<!doctype html><html lang="th"><head><meta charset="utf-8">'
        . '<meta name="viewport" content="width=device-width,initial-scale=1">'
        . '<title>เกิดข้อผิดพลาด</title><style>'
        . 'body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:#f6f5fb;'
        . 'color:#1a1830;display:flex;min-height:100vh;align-items:center;justify-content:center;'
        . 'margin:0;padding:24px}'
        . '.box{background:#fff;border:1px solid #e6e2f2;border-radius:18px;padding:32px;max-width:680px}'
        . 'h1{font-size:20px;margin:0 0 10px}p{color:#6b6880;line-height:1.6;margin:0 0 12px}'
        . 'pre{background:#f0eef9;padding:14px;border-radius:10px;overflow:auto;font-size:13px;'
        . 'white-space:pre-wrap}a{color:#7c3aed}</style></head><body><div class="box">'
        . '<h1>' . $escape($title) . '</h1>';
    if ($showDetail && $detail !== '') {
        echo '<pre>' . $escape($detail) . '</pre>';
    } else {
        echo '<p>กรุณาติดต่อผู้ดูแลระบบ</p>';
    }
    echo '</div></body></html>';
    exit;
}
